server:
  port: 8080

logging:
  path: logs
  file: myTest.log

spring:
  application:
    name: myTest
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_test
    username: root
    password: sansi0906

mybatis:
  type-aliases-package: com.sansi.model
  mapper-locations:
    - mapper/*